"""Design the A-weighting IIR filter (IEC 61672) for a given sample rate.

Generates second-order-section (biquad) coefficients for the firmware and
verifies the response against the IEC 61672 class-2 tolerance band.

Usage:
    python design_a_weighting.py [fs]      # default fs = 16000 Hz

Prints C code ready to paste into src/spl_dsp.c.
"""
import sys

import numpy as np
from scipy import signal

FS = float(sys.argv[1]) if len(sys.argv) > 1 else 16000.0

# Analog A-weighting transfer function (IEC 61672-1), poles in Hz.
F1 = 20.598997
F2 = 107.65265
F3 = 737.86223
F4 = 12194.217
A1000 = 1.9997  # gain normalization at 1 kHz, dB

NUM = [(2 * np.pi * F4) ** 2 * 10 ** (A1000 / 20), 0, 0, 0, 0]
DEN = np.polymul(
    [1, 4 * np.pi * F4, (2 * np.pi * F4) ** 2],
    [1, 4 * np.pi * F1, (2 * np.pi * F1) ** 2],
)
DEN = np.polymul(np.polymul(DEN, [1, 2 * np.pi * F3]), [1, 2 * np.pi * F2])

# Bilinear transform to digital, then split into biquads (SOS).
b, a = signal.bilinear(NUM, DEN, FS)
sos = signal.tf2sos(b, a)

print(f"// A-weighting filter, fs = {FS:.0f} Hz, {len(sos)} biquad sections")
print("// Generated by tools/design_a_weighting.py — do not edit by hand.")
print(f"#define SPL_A_WEIGHT_SECTIONS {len(sos)}")
print("static const float a_weight_sos[SPL_A_WEIGHT_SECTIONS][6] = {")
for sec in sos:
    b0, b1, b2, a0, a1, a2 = sec
    print(f"  {{ {b0:+.10e}f, {b1:+.10e}f, {b2:+.10e}f,")
    print(f"    {a0:+.10e}f, {a1:+.10e}f, {a2:+.10e}f }},")
print("};")

# --- Verification against IEC 61672 class 2 tolerances -----------------------
# Nominal A-weighting values (dB) at third-octave frequencies, and class-2
# tolerance (+/-, dB). Subset from IEC 61672-1 table 2.
nominal = {
    31.5: (-39.4, 2.0), 63: (-26.2, 1.5), 125: (-16.1, 1.5),
    250: (-8.6, 1.4), 500: (-3.2, 1.4), 1000: (0.0, 1.1),
    2000: (1.2, 1.6), 4000: (1.0, 1.6), 6300: (-0.1, 2.1),
}
print("\n// Verificação (freq: resposta do filtro vs nominal IEC, tolerância classe 2):")
ok = True
for f, (nom, tol) in nominal.items():
    if f >= FS / 2:
        continue
    w, h = signal.freqz(b, a, worN=[f], fs=FS)
    db = 20 * np.log10(abs(h[0]))
    flag = "OK" if abs(db - nom) <= tol else "FORA"
    if flag == "FORA":
        ok = False
    print(f"//   {f:7.1f} Hz: {db:+7.2f} dB (nominal {nom:+6.1f} ± {tol}) {flag}")
print(f"// Resultado: {'DENTRO da classe 2' if ok else 'FORA da tolerância — revisar'}")
