"""Design the C-weighting IIR filter (IEC 61672) for a given sample rate.

C(s) = G * s^2 * (2*pi*f4)^2 / [(s + 2*pi*f1)^2 * (s + 2*pi*f4)^2]
f1 = 20.598997 Hz, f4 = 12194.217 Hz, normalizado para 0 dB em 1 kHz.

Emite 2 secoes biquad em layout CMSIS df2T {b0,b1,b2,-a1,-a2} e verifica a
resposta contra os valores nominais IEC 61672 (tolerancia classe 2).

Usage: python design_c_weighting.py [fs]     # default 48000
"""
import sys

import numpy as np
from scipy import signal

FS = float(sys.argv[1]) if len(sys.argv) > 1 else 48000.0

F1 = 20.598997
F4 = 12194.217
C1000 = 0.0619   # ganho de normalizacao em 1 kHz, dB

NUM = [(2 * np.pi * F4) ** 2 * 10 ** (C1000 / 20), 0, 0]
DEN = np.polymul(
    [1, 4 * np.pi * F4, (2 * np.pi * F4) ** 2],
    [1, 4 * np.pi * F1, (2 * np.pi * F1) ** 2],
)

b, a = signal.bilinear(NUM, DEN, FS)
sos = signal.tf2sos(b, a)

print(f"// C-weighting filter, fs = {FS:.0f} Hz, {len(sos)} biquad sections")
print("// Generated by tools/design_c_weighting.py - do not edit by hand.")
print("// Layout CMSIS df2T: {b0, b1, b2, -a1, -a2}.")
print(f"#define SPL_C_WEIGHT_SECTIONS {len(sos)}")
print("static const float c_weight_sos[SPL_C_WEIGHT_SECTIONS][5] = {")
for b0, b1, b2, a0, a1, a2 in sos:
    print(f"  {{ {b0:+.10e}f, {b1:+.10e}f, {b2:+.10e}f,")
    print(f"    {-a1:+.10e}f, {-a2:+.10e}f }},")
print("};")

# Nominal C-weighting (IEC 61672) e tolerancia classe 2.
nominal = {
    31.5: (-3.0, 2.0), 63: (-0.8, 1.5), 125: (-0.2, 1.5), 250: (0.0, 1.4),
    500: (0.0, 1.4), 1000: (0.0, 1.1), 2000: (-0.2, 1.6), 4000: (-0.8, 1.6),
    8000: (-3.0, 3.1), 16000: (-8.5, 17.0),
}
print("\n// Verificacao (resposta vs nominal IEC, classe 2):")
ok = True
for f, (nom, tol) in nominal.items():
    if f >= FS / 2:
        continue
    w, h = signal.freqz(b, a, worN=[f], fs=FS)
    db = 20 * np.log10(abs(h[0]))
    flag = "OK" if abs(db - nom) <= tol else "FORA"
    if flag == "FORA":
        ok = False
    print(f"//   {f:7.1f} Hz: {db:+7.2f} dB (nominal {nom:+5.1f} +/- {tol}) {flag}")
print(f"// Resultado: {'DENTRO da classe 2' if ok else 'FORA - revisar'}")
sys.exit(0 if ok else 1)
