/***************************************************************************//**
 * @file
 * @brief Sound pressure level DSP implementation (CMSIS-DSP accelerated).
 *
 * Pipeline per block: arm_q15_to_float (scale 1/32768) -> raw block feeds the
 * 1/3-octave bank and, when extended metrics are on, a C-weighting cascade
 * with peak hold -> A-weighting in place (arm_biquad_cascade_df2T_f32) ->
 * block energy (arm_power_f32) feeding LAeq, the Fast (125 ms) and Slow (1 s)
 * exponential detectors, and a LAF histogram for the L10/L50/L90 percentiles.
 ******************************************************************************/
#include "spl_dsp.h"

#include <math.h>
#include <string.h>

#include "arm_math.h"
#include "spl_toct.h"

// A-weighting filter, fs = 48000 Hz, 3 biquad sections (b0 b1 b2 a1 a2 with
// H(z) = (b0 + b1 z^-1 + b2 z^-2) / (1 + a1 z^-1 + a2 z^-2)).
// Generated by tools/design_a_weighting.py — do not edit by hand.
// Verified inside IEC 61672 class-2 tolerance from 31.5 Hz to 6.3 kHz.
#define SPL_A_WEIGHT_SECTIONS 3
static const float a_weight_sos[SPL_A_WEIGHT_SECTIONS][5] = {
  { +2.3430179230e-01f, +4.6860358460e-01f, +2.3430179230e-01f,
    -2.2455845806e-01f, +1.2606625272e-02f },
  { +1.0000000000e+00f, -2.0001524740e+00f, +1.0001524856e+00f,
    -1.8938704945e+00f, +8.9515976894e-01f },
  { +1.0000000000e+00f, -1.9998475260e+00f, +9.9984753766e-01f,
    -1.9946144562e+00f, +9.9462170719e-01f },
};

// C-weighting filter, fs = 48000 Hz, 2 biquad sections.
// Generated by tools/design_c_weighting.py — do not edit by hand.
// Layout CMSIS df2T: {b0, b1, b2, -a1, -a2}. Class-2 verified 31.5 Hz-16 kHz.
#define SPL_C_WEIGHT_SECTIONS 2
static const float c_weight_sos[SPL_C_WEIGHT_SECTIONS][5] = {
  { +1.9788712003e-01f, +3.9577424005e-01f, +1.9788712003e-01f,
    +2.2455845806e-01f, -1.2606625272e-02f },
  { +1.0000000000e+00f, -2.0000000000e+00f, +1.0000000000e+00f,
    +1.9946144560e+00f, -9.9462170701e-01f },
};

/// Time weighting constants (IEC 61672): Fast 125 ms, Slow 1 s.
#define FAST_TAU_S 0.125f
#define SLOW_TAU_S 1.0f

/// Guard against log10(0) in silence.
#define MIN_MEAN_SQUARE 1e-12f

/// Largest block mic_pdm delivers (sized for 8 ms at 48 kHz).
#define MAX_BLOCK_FRAMES 384u

/// LAF histogram for the percentiles: 0.5 dB bins from -10 to +150 dB(A).
#define HIST_MIN_DB   (-10.0f)
#define HIST_BINS     320u
#define HIST_STEP_DB  0.5f

// CMSIS-DSP biquad cascade (direct form II transposed) for A-weighting.
static float32_t biquad_coeffs[SPL_A_WEIGHT_SECTIONS * 5];
static float32_t biquad_state[SPL_A_WEIGHT_SECTIONS * 2];
static arm_biquad_cascade_df2T_instance_f32 biquad;

// C-weighting runs as a manual per-sample loop (no output buffer needed,
// only the running peak).
static float c_state[SPL_C_WEIGHT_SECTIONS][2];

// Scratch for the float samples of one block.
static float32_t block_f32[MAX_BLOCK_FRAMES];

static float cal_offset_db = SPL_DSP_DEFAULT_CAL_OFFSET_DB;
static bool extended_enabled;

// Exponential detectors (mean square, A-weighted). Negative = not settled
// yet (first block seeds them, avoiding the boot/DC-step artifact).
static float fast_ms = -1.0f;
static float slow_ms = -1.0f;
// alpha cache for the last seen block size.
static uint32_t alpha_block_n;
static float alpha_fast;
static float alpha_slow;

// Interval accumulators.
static float sum_squares;
static uint32_t n_acc;
static float max_fast_ms;
static float min_fast_ms;
static float max_slow_ms;
static float min_slow_ms;
static float peak_c_abs;
static uint32_t laf_hist[HIST_BINS];
static uint32_t laf_hist_n;

void spl_dsp_init(void)
{
  for (int s = 0; s < SPL_A_WEIGHT_SECTIONS; s++) {
    biquad_coeffs[s * 5 + 0] = a_weight_sos[s][0];
    biquad_coeffs[s * 5 + 1] = a_weight_sos[s][1];
    biquad_coeffs[s * 5 + 2] = a_weight_sos[s][2];
    biquad_coeffs[s * 5 + 3] = -a_weight_sos[s][3];   // CMSIS expects -a1
    biquad_coeffs[s * 5 + 4] = -a_weight_sos[s][4];   // CMSIS expects -a2
  }
  arm_biquad_cascade_df2T_init_f32(&biquad, SPL_A_WEIGHT_SECTIONS,
                                   biquad_coeffs, biquad_state);
  memset(c_state, 0, sizeof(c_state));

  fast_ms = -1.0f;
  slow_ms = -1.0f;
  alpha_block_n = 0;
  sum_squares = 0.0f;
  n_acc = 0;
  max_fast_ms = MIN_MEAN_SQUARE;
  min_fast_ms = -1.0f;
  max_slow_ms = MIN_MEAN_SQUARE;
  min_slow_ms = -1.0f;
  peak_c_abs = 0.0f;
  memset(laf_hist, 0, sizeof(laf_hist));
  laf_hist_n = 0;
}

void spl_dsp_set_extended(bool enabled)
{
  extended_enabled = enabled;
}

void spl_dsp_set_cal_offset(float offset_db)
{
  cal_offset_db = offset_db;
}

float spl_dsp_get_cal_offset(void)
{
  return cal_offset_db;
}

static float ms_to_db(float ms)
{
  if (ms < MIN_MEAN_SQUARE) {
    ms = MIN_MEAN_SQUARE;
  }
  return 10.0f * log10f(ms) + cal_offset_db;
}

/// C-weighting (df2T manual, coefficients already {b0,b1,b2,-a1,-a2}) with
/// running peak hold — no output buffer.
static void c_weight_peak(const float32_t *x, uint32_t n)
{
  float peak = peak_c_abs;
  for (uint32_t i = 0; i < n; i++) {
    float v = x[i];
    for (int s = 0; s < SPL_C_WEIGHT_SECTIONS; s++) {
      const float *c = c_weight_sos[s];
      float y = c[0] * v + c_state[s][0];
      c_state[s][0] = c[1] * v + c[3] * y + c_state[s][1];
      c_state[s][1] = c[2] * v + c[4] * y;
      v = y;
    }
    float a = fabsf(v);
    if (a > peak) {
      peak = a;
    }
  }
  peak_c_abs = peak;
}

void spl_dsp_process_block(const int16_t *samples, uint32_t n)
{
  if (n == 0 || n > MAX_BLOCK_FRAMES) {
    return;
  }

  // q15 -> float in [-1, 1); the RAW block feeds the 1/3-octave bank and the
  // C-weighted peak detector before the A-weighting overwrites it in place.
  arm_q15_to_float((const q15_t *)samples, block_f32, n);
  spl_toct_process_block(block_f32, n);
  if (extended_enabled) {
    c_weight_peak(block_f32, n);
  }
  arm_biquad_cascade_df2T_f32(&biquad, block_f32, block_f32, n);

  float32_t block_sum_sq;
  arm_power_f32(block_f32, n, &block_sum_sq);

  // LAeq accumulation over the whole interval.
  sum_squares += block_sum_sq;
  n_acc += n;

  // Exponential detectors with alpha = 1 - exp(-T_block / tau).
  if (n != alpha_block_n) {
    alpha_block_n = n;
    float t_block = (float)n / (float)SPL_DSP_SAMPLE_RATE_HZ;
    alpha_fast = 1.0f - expf(-t_block / FAST_TAU_S);
    alpha_slow = 1.0f - expf(-t_block / SLOW_TAU_S);
  }
  float block_ms = block_sum_sq / (float)n;
  fast_ms = (fast_ms < 0.0f) ? block_ms : fast_ms + alpha_fast * (block_ms - fast_ms);
  slow_ms = (slow_ms < 0.0f) ? block_ms : slow_ms + alpha_slow * (block_ms - slow_ms);

  if (fast_ms > max_fast_ms) {
    max_fast_ms = fast_ms;
  }
  if (min_fast_ms < 0.0f || fast_ms < min_fast_ms) {
    min_fast_ms = fast_ms;
  }

  if (extended_enabled) {
    if (slow_ms > max_slow_ms) {
      max_slow_ms = slow_ms;
    }
    if (min_slow_ms < 0.0f || slow_ms < min_slow_ms) {
      min_slow_ms = slow_ms;
    }

    // LAF sampled once per block (125 Hz) into the percentile histogram.
    float laf = ms_to_db(fast_ms);
    int bin = (int)((laf - HIST_MIN_DB) / HIST_STEP_DB);
    if (bin < 0) {
      bin = 0;
    }
    if (bin >= (int)HIST_BINS) {
      bin = HIST_BINS - 1;
    }
    laf_hist[bin]++;
    laf_hist_n++;
  }
}

/// Level exceeded @p percent of the time, from the top of the histogram.
static float percentile_db(float percent)
{
  if (laf_hist_n == 0) {
    return ms_to_db(0.0f);
  }
  uint32_t target = (uint32_t)((percent / 100.0f) * (float)laf_hist_n);
  if (target == 0) {
    target = 1;
  }
  uint32_t cum = 0;
  for (int bin = HIST_BINS - 1; bin >= 0; bin--) {
    cum += laf_hist[bin];
    if (cum >= target) {
      return HIST_MIN_DB + (bin + 0.5f) * HIST_STEP_DB;
    }
  }
  return HIST_MIN_DB;
}

bool spl_dsp_close_interval(spl_result_t *out)
{
  if (n_acc == 0) {
    return false;
  }

  out->laeq_db = ms_to_db(sum_squares / (float)n_acc);
  out->lafmax_db = ms_to_db(max_fast_ms);
  out->n_samples = n_acc;

  out->extended = extended_enabled;
  if (extended_enabled) {
    out->lafmin_db = ms_to_db(min_fast_ms < 0.0f ? 0.0f : min_fast_ms);
    out->lasmax_db = ms_to_db(max_slow_ms);
    out->lasmin_db = ms_to_db(min_slow_ms < 0.0f ? 0.0f : min_slow_ms);
    // Peak: 20*log10(|x|peak) shares the mean-square calibration constant
    // (full-scale sine: RMS ref includes the 3.01 dB crest factor).
    float p = (peak_c_abs > 1e-7f) ? peak_c_abs : 1e-7f;
    out->lcpeak_db = 20.0f * log10f(p) + cal_offset_db;
    out->lae_db = out->laeq_db
                  + 10.0f * log10f((float)n_acc / (float)SPL_DSP_SAMPLE_RATE_HZ);
    out->l10_db = percentile_db(10.0f);
    out->l50_db = percentile_db(50.0f);
    out->l90_db = percentile_db(90.0f);
  }

  sum_squares = 0.0f;
  n_acc = 0;
  // Detectors keep running across intervals; extrema restart from the
  // current level so events spanning two intervals register in both.
  max_fast_ms = (fast_ms < 0.0f) ? MIN_MEAN_SQUARE : fast_ms;
  min_fast_ms = fast_ms;
  max_slow_ms = (slow_ms < 0.0f) ? MIN_MEAN_SQUARE : slow_ms;
  min_slow_ms = slow_ms;
  peak_c_abs = 0.0f;
  memset(laf_hist, 0, sizeof(laf_hist));
  laf_hist_n = 0;

  return true;
}

float spl_dsp_current_laf_db(void)
{
  return ms_to_db(fast_ms < 0.0f ? 0.0f : fast_ms);
}
