/***************************************************************************//**
 * @file
 * @brief Sound pressure level DSP implementation (CMSIS-DSP accelerated).
 *
 * Pipeline per block: arm_q15_to_float (scale 1/32768) -> A-weighting as a
 * 3-stage biquad cascade (arm_biquad_cascade_df2T_f32, uses the M33
 * FPU/DSP extension) -> arm_power_f32 for the block energy feeding the
 * LAeq accumulator and the Fast (tau = 125 ms) exponential detector.
 ******************************************************************************/
#include "spl_dsp.h"

#include <math.h>

#include "arm_math.h"

// A-weighting filter, fs = 32000 Hz, 3 biquad sections (b0 b1 b2 a1 a2 with
// H(z) = (b0 + b1 z^-1 + b2 z^-2) / (1 + a1 z^-1 + a2 z^-2)).
// Generated by tools/design_a_weighting.py — do not edit by hand.
// Verified inside IEC 61672 class-2 tolerance from 31.5 Hz to 6.3 kHz.
#define SPL_A_WEIGHT_SECTIONS 3
static const float a_weight_sos[SPL_A_WEIGHT_SECTIONS][5] = {
  { +3.4345833868e-01f, +6.8691667736e-01f, +3.4345833868e-01f,
    +1.7947173147e-01f, +8.0525255991e-03f },
  { +1.0000000000e+00f, -2.0002657179e+00f, +1.0002657532e+00f,
    -1.8439906561e+00f, +8.4681632410e-01f },
  { +1.0000000000e+00f, -1.9997342821e+00f, +9.9973431739e-01f,
    -1.9919271186e+00f, +9.9194341141e-01f },
};

/// Fast time weighting constant (IEC 61672): tau = 125 ms.
#define FAST_TAU_S 0.125f

/// Guard against log10(0) in silence.
#define MIN_MEAN_SQUARE 1e-12f

/// Largest block mic_pdm delivers (sized for 10 ms at 32 kHz).
#define MAX_BLOCK_FRAMES 320u

// CMSIS-DSP biquad cascade (direct form II transposed).
// Coefficient layout per stage: {b0, b1, b2, -a1, -a2}.
static float32_t biquad_coeffs[SPL_A_WEIGHT_SECTIONS * 5];
static float32_t biquad_state[SPL_A_WEIGHT_SECTIONS * 2];
static arm_biquad_cascade_df2T_instance_f32 biquad;

// Scratch for the float samples of one block.
static float32_t block_f32[MAX_BLOCK_FRAMES];

static float cal_offset_db = SPL_DSP_DEFAULT_CAL_OFFSET_DB;

// Fast exponential detector state (mean square, A-weighted).
static float fast_ms;
// alpha cache for the last seen block size.
static uint32_t alpha_block_n;
static float alpha;

// Interval accumulators.
static float sum_squares;
static uint32_t n_acc;
static float max_fast_ms;

void spl_dsp_init(void)
{
  for (int s = 0; s < SPL_A_WEIGHT_SECTIONS; s++) {
    biquad_coeffs[s * 5 + 0] = a_weight_sos[s][0];
    biquad_coeffs[s * 5 + 1] = a_weight_sos[s][1];
    biquad_coeffs[s * 5 + 2] = a_weight_sos[s][2];
    biquad_coeffs[s * 5 + 3] = -a_weight_sos[s][3];   // CMSIS expects -a1
    biquad_coeffs[s * 5 + 4] = -a_weight_sos[s][4];   // CMSIS expects -a2
  }
  arm_biquad_cascade_df2T_init_f32(&biquad, SPL_A_WEIGHT_SECTIONS,
                                   biquad_coeffs, biquad_state);

  fast_ms = MIN_MEAN_SQUARE;
  alpha_block_n = 0;
  sum_squares = 0.0f;
  n_acc = 0;
  max_fast_ms = MIN_MEAN_SQUARE;
}

void spl_dsp_set_cal_offset(float offset_db)
{
  cal_offset_db = offset_db;
}

float spl_dsp_get_cal_offset(void)
{
  return cal_offset_db;
}

static float ms_to_db(float ms)
{
  if (ms < MIN_MEAN_SQUARE) {
    ms = MIN_MEAN_SQUARE;
  }
  return 10.0f * log10f(ms) + cal_offset_db;
}

void spl_dsp_process_block(const int16_t *samples, uint32_t n)
{
  if (n == 0 || n > MAX_BLOCK_FRAMES) {
    return;
  }

  // q15 -> float in [-1, 1), A-weighting cascade in place, block energy.
  arm_q15_to_float((const q15_t *)samples, block_f32, n);
  arm_biquad_cascade_df2T_f32(&biquad, block_f32, block_f32, n);

  float32_t block_sum_sq;
  arm_power_f32(block_f32, n, &block_sum_sq);

  // LAeq accumulation over the whole interval.
  sum_squares += block_sum_sq;
  n_acc += n;

  // Fast detector: exponential average of the block mean square with
  // alpha = 1 - exp(-T_block / tau).
  if (n != alpha_block_n) {
    alpha_block_n = n;
    alpha = 1.0f - expf(-((float)n / (float)SPL_DSP_SAMPLE_RATE_HZ) / FAST_TAU_S);
  }
  float block_ms = block_sum_sq / (float)n;
  fast_ms += alpha * (block_ms - fast_ms);

  if (fast_ms > max_fast_ms) {
    max_fast_ms = fast_ms;
  }
}

bool spl_dsp_close_interval(spl_result_t *out)
{
  if (n_acc == 0) {
    return false;
  }

  out->laeq_db = ms_to_db(sum_squares / (float)n_acc);
  out->lafmax_db = ms_to_db(max_fast_ms);
  out->n_samples = n_acc;

  sum_squares = 0.0f;
  n_acc = 0;
  // Fast detector keeps running across intervals; the max restarts from the
  // current level so a tone spanning two intervals registers in both.
  max_fast_ms = fast_ms;

  return true;
}

float spl_dsp_current_laf_db(void)
{
  return ms_to_db(fast_ms);
}
